//
//  BibleContextsTable.m
//  HanbitBibleMemory
//
//  Created by Jaehong Chon on 11/5/13.
//  Copyright (c) 2013 Hanbit Church. All rights reserved.
//

#import "BibleContextsTable.h"

NSString* const korCategoryString[5] =
{
    @"A. 새로운 삶",
    @"B. 그리스도를 전파함",
    @"C. 하나님을 의뢰함",
    @"D. 그리스도 제자의 자격",
    @"E. 그리스도를 닮아 감",
};

NSString* const korTitleString[5][12] =
{
    {@"고린도후서 5:17",
     @"갈라디아서 2:20",
     @"로마서 12:1",
     @"요한복음 14:21",
     @"디모데후서 3:16",
     @"여호수아 1:8",
     @"요한복음 15:7",
     @"빌립보서 4:6,7",
     @"마태복음 18:20",
     @"히브리서 10:24,25",
     @"마태복음 4:19",
     @"로마서 1:16",},
    
    {@"로마서 3:23",
     @"이사야 53:6",
     @"로마서 6:23",
     @"히브리서 9:27",
     @"로마서 5:8",
     @"베드로전서 3:18",
     @"에베소서 2:8,9",
     @"디도서 3:5",
     @"요한복음 1:12",
     @"요한계시록 3:20",
     @"요한일서 5:13",
     @"요한복음 5:24",},
    
    {@"고린도전서 3:16",
     @"고린도전서 2:12",
     @"이사야 41:10",
     @"빌립보서 4:13",
     @"예레미야애가 3:22,23",
     @"민수기 23:19",
     @"이사야 26:3",
     @"베드로전서 5:7",
     @"로마서 8:32",
     @"빌립보서 4:19",
     @"히브리서 2:18",
     @"시편 119:9,11",},
    
    {@"마태복음 6:33",
     @"누가복음 9:23",
     @"요한일서 2:15,16",
     @"로마서 12:2",
     @"고린도전서 15:58",
     @"히브리서 12:3",
     @"마가복음 10:45",
     @"고린도후서 4:5",
     @"잠언 3:9,10",
     @"고린도후서 9:6,7",
     @"사도행전 1:8",
     @"마태복음 28:19,20",},
    
    {@"요한복음 13:34,35",
     @"요한일서 3:18",
     @"빌립보서 2:3,4",
     @"베드로전서 5:5,6",
     @"에베소서 5:3",
     @"베드로전서 2:11",
     @"레위기 19:11",
     @"사도행전 24:16",
     @"히브리서 11:6",
     @"로마서 4:20,21",
     @"갈라디아서 6:9,10",
     @"마태복음 5:16",},
};

NSString* const korMidTitleString[5][6] =
{
    {@"중심되신 그리스도",
     @"그리스도께 순종",
     @"말씀",
     @"기도",
     @"교제",
     @"증거",},
    
    {@"모든 사람이 죄를 범함",
     @"죄의 형벌",
     @"그리스도가 형벌을 받음",
     @"선행으로 구원받지 못함",
     @"그리스도를 모셔야 함",
     @"구원의 확신",},
    
    {@"성령",
     @"능력",
     @"성실",
     @"평안",
     @"공급",
     @"유혹에서 도우심",},
    
    {@"그리스도를 첫자리에 모심",
     @"죄에서 떠남",
     @"견고함",
     @"다른 사람을 섬김",
     @"후히 드릴 것",
     @"세계 비전",},
    
    {@"사랑",
     @"겸손",
     @"순결",
     @"정직",
     @"믿음",
     @"선행",},
};

NSString* const korTextString[5][12] =
{
    {@"그런즉 누구든지 그리스도 안에 있으면 새로운 피조물이라. 이전 것은 지나갔으니, 보라 새것이 되었도다.",
     @"내가 그리스도와 함께 십자가에 못 박혔나니, 그런즉 이제는 내가 산것이 아니요 오직 내안에 그리스도께서 사신 것이라. 이제 내가 육체 가운데 사는 것은 나를 사랑하사 나를 위하여 자기 몸을 버리신 하나님의 아들을 믿는 믿음안에서 사는 것이라.",
     @"그러므로 형제들아, 내가 하나님의 모든 자비하심으로 너희를 권하노니, 너희 몸을 하나님이 기뻐하시는 거룩한 산제사로 드리라. 이는 너희의 드릴 영적 예배니라.",
     @"나의 계명을 가지고 지키는 자라야 나를 사랑하는 자니, 나를 사랑하는 자는 내 아버지께 사랑을 받을 것이요 나도 그를 사랑하여 그에게 나를 나타내리라.",
     @"모든 성경은 하나님의 감동으로 된 것으로, 교훈과 책망과 바르게 함과 의로 교육하기에 유익하니.",
     @"이 율법책을 네 입에서 떠나지 말게 하며 주야로 그것을 묵상하여 그 가운데 기록한 대로 다 지켜 행하라. 그리하면 네 길이 평탄하게 될 것이라. 네가 형통하리라.",
     @"너희가 내안에 거하고 내 말이 너희 안에 거하면 무엇이든지 원하는 대로 구하라. 그리하면 이루리라.",
     @"아무것도 염려하지 말고 오직 모든 일에 기도와 간구로 너희 구할 것을 감사함으로 하나님께 아뢰라. 그리하면 모든 지각에 뛰어난 하나님의 평강이 그리스도 예수 안에서 너희 마음과 생각을 지키시리라.",
     @"두세 사람이 내이름으로 모인 곳에는 나도 그들 중에 있느니라.",
     @"서로 돌아보아 사랑과 선행을 격려하며, 모이기를 폐하는 어떤 사람들의 습관과 같이 하지말고, 오직 권하여 그날이 가까움을 볼수록 더욱 그리하자.",
     @"말씀하시되, 나를 따라오너라 내가 너희로 사람을 낚는 어부가 되게 하리라 하시니.",
     @"내가 복음을 부끄러워하지 아니하노니, 이 복음은 모든 믿는 자에게 구원을 주시는 하나님의 능력이 됨이라. 첫째는 유대인에게요 또한 헬라인에게로다.",},
    
    {@"모든 사람이 죄를 범하였으매 하나님의 영광에 이르지 못하더니.",
     @"우리는 다 양 같아서 그릇 행하여 각기 제 길로 갔거늘, 여호와께서는 우리 무리의 죄악을 그에게 담당시키셨도다.",
     @"죄의 삯은 사망이요, 하나님의 은사는 그리스도 예수 우리 주 안에 있는 영생이니라.",
     @"한 번 죽는 것은 사람에게 정하신 것이요, 그 후에는 심판이 있으리니.",
     @"우리가 아직 죄인 되었을 때에 그리스도께서 우리를 위하여 죽으심으로 하나님께서 우리에게 대한 자기의 사랑을 확증하셨느니라.",
     @"그리스도께서도 한 번 죄를 위하여 죽으사 의인으로서 불의한 자를 대신하셨으니, 이는 우리를 하나님 앞으로 인도하려 하심이라. 육체로는 죽임을 당하시고 영으로는 살리심을 받으셨으니.",
     @"너희가 그 은혜를 인하여 믿음으로 말미암아 구원을 얻었나니, 이것이 너희에게서 난 것이 아니요 하나님의 선물이라. 행위에서 난 것이 아니니, 이는 누구든지 자랑치 못하게 함이니라.",
     @"우리를 구원하시되 우리의 행한바 의로운 행위로 말미암지 아니하고, 오직 그의 긍휼하심을 좇아 중생의 씻음과 성령의 새롭게 하심으로 하셨나니.",
     @"영접하는 자 곧 그 이름을 믿는 자들에게는 하나님의 자녀가 되는 권세를 주셨으니.",
     @"볼지어다. 내가 문밖에 서서 두드리노니, 누구든지 내 음성을 듣고 문을 열면 내가 그에게로 들어가 그로 더불어 먹고 그는 나로 더불어 먹으리라.",
     @"내가 하나님의 아들의 이름을 믿는 너희에게 이것을 쓴 것은, 너희로 하여금 너희에게 영생이 있음을 알게 하려 함이라.",
     @"내가 진실로 진실로 너희에게 이르노니, 내 말을 듣고 또 나 보내신 이를 믿는 자는 영생을 얻었고 심판에 이르지 아니하나니 사망에서 생명으로 옮겼느니라.",},
    
    {@"너희가 하나님의 성전인 것과 하나님의 성령이 너희 안에 거하시는 것을 알지 못하느뇨.",
     @"우리가 세상의 영을 받지 아니하고 오직 하나님께로 온 영을 받았으니, 이는 우리로 하여금 하나님께서 우리에게 은혜로 주신 것들을 알게 하려 하심이라.",
     @"두려워 말라. 내가 너와 함께함이니라. 놀라지 말라. 나는 네 하나님이 됨이니라. 내가 너를 굳세게 하리라. 참으로 너를 도와주리라. 참으로 나의 의로운 오른손으로 너를 붙들리라.",
     @"내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.",
     @"여호와의 자비와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다. 이것이 아침마다 새로우니 주의 성실이 크도소이다.",
     @"하나님은 인생이 아니시니 식언치 않으시고 인자가 아니시니 후회가 없으시도다. 어찌 그 말씀하신 바를 행치 않으시며 하신 말씀을 실행치 않으시랴.",
     @"주께서 심지가 견고한 자를 평강에 평강으로 지키시리니, 이는 그가 주를 의뢰함이니이다.",
     @"너희 염려를 다 주께 맡겨 버리라. 이는 저가 너희를 권고하심이니라.",
     @"자기 아들을 아끼지 아니하시고 우리 모든 사람을 위하여 내어 주신 이가 어찌 그 아들과 함께 모든 것을 우리에게 은사로 주지 아니하시겠느뇨.",
     @"나의 하나님이 그리스도 예수 안에서 영광 가운데 그 풍성한 대로 너희 모든 쓸 것을 채우시리라.",
     @"자기가 시험을 받아 고난을 당하셨은즉 시험받는 자들을 능히 도우시느니라.",
     @"청년이 무엇으로 그 행실을 깨끗케 하리이까. 주의 말씀을 따라 삼갈 것이니이다. 내가 주께 범죄치 아니하려 하여 주의 말씀을 내 마음에 두었나이다.",},
    
    {@"너희는 먼저 그의 나라와 그의 의를 구하라. 그리하면 이 모든 것을 너희에게 더하시리라.",
     @"또 무리에게 이르시되, 아무든지 나를 따라오려거든 자기를 부인하고 날마다 제 십자가를 지고 나를 좇을 것이니라.",
     @"이 세상이나 세상에 있는 것들을 사랑치 말라. 누구든지 세상을 사랑하면 아버지의 사랑이 그 속에 있지 아니하니, 이는 세상에 있는 모든 것이 육신의 정욕과 안목의 정욕과 이생의 자랑이니, 다 아버지께로 좇아 온 것이 아니요 세상으로 좇아 온 것이라.",
     @"너희는 이 세대를 본받지 말고 오직 마음을 새롭게 함으로 변화를 받아 하나님의 선하시고 기뻐하시고 온전하신 뜻이 무엇인지 분별하도록 하라.",
     @"그러므로 내 사랑하는 형제들아, 견고하며 흔들리지 말며 항상 주의 일에 더욱 힘쓰는 자들이 되라. 이는 너희 수고가 주 안에서 헛되지 않은 줄을 앎이니라.",
     @"너희가 피곤하여 낙심치 않기 위하여 죄인들의 이같이 자기에게 거역한 일을 참으신자를 생각하라.",
     @"인자의 온 것은 섬김을 받으려 함이 아니라 도리어 섬기려 하고 자기 목숨을 많은 사람의 대속물로 주려 함이니라.",
     @"우리가 우리를 전파하는 것이 아니라 오직 그리스도 예수의 주 되신 것과 또 예수를 위하여 우리가 너희의 종 된 것을 전파함이라.",
     @"네 재물과 네 소산물의 처음 익은 열매로 여호와를 공경하라. 그리하면 네 창고가 가득히 차고 네 즙틀에 새 포도즙이 넘치리라.",
     @"이것이 곧 적게 심는 자는 적게 거두고 많이 심는 자는 많이 거둔다 하는 말이로다. 각각 그 마음에 정한 대로 할 것이요 인색함으로나 억지로 하지 말지니 하나님은 즐겨 내는 자를 사랑하시느니라.",
     @"오직 성령이 너희에게 임하시면 너희가 권능을 받고 예루살렘과 온 유대와 사마리아와 땅 끝까지 이르러 내 증인이 되리라 하시니라.",
     @"그러므로 너희는 가서 모든 족속으로 제자를 삼아 아버지와 아들과 성령의 이름으로 세례를 주고, 내가 너희에게 분부한 모든 것을 가르쳐 지키게 하라. 볼지어다. 내가 세상 끝 날까지 너희와 항상 함께 있으리라 하시니라.",},
    
    {@"새 계명을 너희에게 주노니 서로 사랑하라. 내가 너희를 사랑한 것같이 너희도 서로 사랑하라. 너희가 서로 사랑하면 이로써 모든 사람이 너희가 내 제자인 줄 알리라.",
     @"자녀들아, 우리가 말과 혀로만 사랑하지 말고 오직 행함과 진실함으로 하자.",
     @"아무 일에든지 다툼이나 허영으로 하지 말고 오직 겸손한 마음으로 각각 자기보다 남을 낫게 여기고, 각각 자기 일을 돌아볼 뿐더러 또한 각각 다른 사람들의 일을 돌아보아 나의 기쁨을 충만케 하라.",
     @"젊은 자들아, 이와 같이 장로들에게 순복하고 다 서로 겸손으로 허리를 동이라. 하나님이 교만한 자를 대적하시되 겸손한 자들에게는 은혜를 주시느니라. 그러므로 하나님의 능하신 손 아래서 겸손하라. 때가 되면 너희를 높이시리라.",
     @"음행과 온갖 더러운 것과 탐욕은 너희 중에서 그 이름이라도 부르지 말라. 이는 성도의 마땅한 바니라.",
     @"사랑하는 자들아, 나그네와 행인 같은 너희를 권하노니 영혼을 거스려 싸우는 육체의 정욕을 제어하라.",
     @"너희는 도적질하지 말며, 속이지 말며, 서로 거짓말하지 말며.",
     @"이것을 인하여 나도 하나님과 사람을 대하여 항상 양심에 거리낌이 없기를 힘쓰노라.",
     @"믿음이 없이는 기쁘시게 못하나니, 하나님께 나아가는 자는 반드시 그가 계신 것과 또한 그가 자기를 찾는 자들에게 상 주시는 이심을 믿어야 할지니라.",
     @"믿음이 없어 하나님의 약속을 의심치 않고, 믿음에 견고하여져서 하나님께 영광을 돌리며, 약속하신 그것을 또한 능히 이루실 줄을 확신하였으니.",
     @"우리가 선을 행하되 낙심하지 말지니 피곤하지 아니하면 때가 이르매 거두리라. 그러므로 우리는 기회 있는 대로 모든 이에게 착한 일을 하되 더욱 믿음의 가정들에게 할지니라.",
     @"이같이 너희 빛을 사람 앞에 비취게 하여 저희로 너희 착한 행실을 보고 하늘에 계신 너희 아버지께 영광을 돌리게 하라."},
};

NSString* const korHintTextString[5][12] =
{
    {@"그ㅁㅁ 누ㅁㅁㅁ 그ㅁㅁㅁ 안ㅁ 있ㅁㅁ 새ㅁㅁ 피ㅁㅁㅁㅁ. 이ㅁ 것ㅁ 지ㅁㅁㅁㅁ, 보ㅁ 새ㅁㅁ 되ㅁㅁㅁ.",
     @"내ㅁ 그ㅁㅁㅁㅁ 함ㅁ 십ㅁㅁㅁ 못 박ㅁㅁㅁ, 그ㅁㅁ 이ㅁㅁ 내ㅁ 산ㅁㅁ 아ㅁㅁ 오ㅁ 내ㅁㅁ 그ㅁㅁㅁㅁㅁ 사ㅁ 것ㅁㅁ. 이ㅁ 내ㅁ 육ㅁ 가ㅁㅁ 사ㅁ 것ㅁ 나ㅁ 사ㅁㅁㅁ 나ㅁ 위ㅁㅁ 자ㅁ 몸ㅁ 버ㅁㅁ 하ㅁㅁㅁ 아ㅁㅁ 믿ㅁ 믿ㅁㅁㅁㅁ 사ㅁ 것ㅁㅁ.",
     @"그ㅁㅁㅁ 형ㅁㅁㅁ, 내ㅁ 하ㅁㅁㅁ 모든 자ㅁㅁㅁㅁㅁ 너ㅁㅁ 권ㅁㅁㅁ, 너ㅁ 몸ㅁ 하ㅁㅁㅁ 기ㅁㅁㅁㅁ 거ㅁㅁ 산ㅁㅁㅁ 드ㅁㅁ. 이ㅁ 너ㅁㅁ 드ㅁ 영ㅁ 예ㅁㅁㅁ.",
     @"나ㅁ 계ㅁㅁ 가ㅁㅁ 지ㅁㅁ 자ㅁㅁ 나ㅁ 사ㅁㅁㅁ 자ㅁ, 나ㅁ 사ㅁㅁㅁ 자ㅁ 내 아ㅁㅁㅁ 사ㅁㅁ 받ㅁ 것ㅁㅁ 나ㅁ 그ㅁ 사ㅁㅁㅁ 그ㅁㅁ 나ㅁ 나ㅁㅁㅁㅁ.",
     @"모ㅁ 성ㅁㅁ 하ㅁㅁㅁ 감ㅁㅁㅁ 된 것ㅁㅁ, 교ㅁㅁ 책ㅁㅁ 바ㅁㅁ 함ㅁ 의ㅁ 교ㅁㅁㅁㅁ 유ㅁㅁㅁ.",
     @"이 율ㅁㅁㅁ 네 입ㅁㅁ 떠ㅁㅁ 말ㅁ 하ㅁ 주ㅁㅁ 그ㅁㅁ 묵ㅁㅁㅁ 그 가ㅁㅁ 기ㅁㅁ 대ㅁ 다 지ㅁ 행ㅁㅁ. 그ㅁㅁㅁ 네 길ㅁ 평ㅁㅁㅁ 될 것ㅁㅁ. 네ㅁ 형ㅁㅁㅁㅁ.",
     @"너ㅁㅁ 내ㅁㅁ 거ㅁㅁ 내 말ㅁ 너ㅁ 안ㅁ 거ㅁㅁ 무ㅁㅁㅁㅁ 원ㅁㅁ 대ㅁ 구ㅁㅁ. 그ㅁㅁㅁ 이ㅁㅁㅁ.",
     @"아ㅁㅁㅁ 염ㅁㅁㅁ 말ㅁ 오ㅁ 모ㅁ 일ㅁ 기ㅁㅁ 간ㅁㅁ 너ㅁ 구ㅁ 것ㅁ 감ㅁㅁㅁㅁ 하ㅁㅁㅁ 아ㅁㅁ. 그ㅁㅁㅁ 모ㅁ 지ㅁㅁ 뛰ㅁㅁ 하ㅁㅁㅁ 평ㅁㅁ 그ㅁㅁㅁ 예ㅁ 안ㅁㅁ 너ㅁ 마ㅁㅁ 생ㅁㅁ 지ㅁㅁㅁㅁ.",
     @"두ㅁ 사ㅁㅁ 내ㅁㅁㅁㅁ 모ㅁ 곳ㅁㅁ 나ㅁ 그ㅁ 중ㅁ 있ㅁㅁㅁ.",
     @"서ㅁ 돌ㅁㅁㅁ 사ㅁㅁ 선ㅁㅁ 격ㅁㅁㅁ, 모ㅁㅁㅁ 폐ㅁㅁ 어ㅁ 사ㅁㅁㅁ 습ㅁㅁ 같ㅁ 하ㅁㅁㅁ, 오ㅁ 권ㅁㅁ 그ㅁㅁ 가ㅁㅁㅁ 볼ㅁㅁ 더ㅁ 그ㅁㅁㅁ.",
     @"말ㅁㅁㅁㅁ, 나ㅁ 따ㅁㅁㅁㅁ 내ㅁ 너ㅁㅁ 사ㅁㅁ 낚ㅁ 어ㅁㅁ 되ㅁ 하ㅁㅁ 하ㅁㅁ.",
     @"내ㅁ 복ㅁㅁ 부ㅁㅁㅁㅁㅁ 아ㅁㅁㅁㅁ, 이 ㅁㅁㅁ 모ㅁ 믿ㅁ 자ㅁㅁ 구ㅁㅁ 주ㅁㅁ 하ㅁㅁㅁ 능ㅁㅁ 됨ㅁㅁ. 첫ㅁㅁ 유ㅁㅁㅁㅁㅁ 또ㅁ 헬ㅁㅁㅁㅁㅁㅁ.",},

    {@"모ㅁ 사ㅁㅁ 죄ㅁ 범ㅁㅁㅁㅁ 하ㅁㅁㅁ 영ㅁㅁ 이ㅁㅁ 못ㅁㅁㅁ.",
     @"우ㅁㅁ 다 양 같ㅁㅁ 그ㅁ 행ㅁㅁ 각ㅁ 제 길ㅁ 갔ㅁㅁ, 여ㅁㅁㅁㅁㅁ 우ㅁ 무ㅁㅁ 죄ㅁㅁ 그ㅁㅁ 담ㅁㅁㅁㅁㅁㅁ.",
     @"죄ㅁ 삯ㅁ 사ㅁㅁㅁ, 하ㅁㅁㅁ 은ㅁㅁ 그ㅁㅁㅁ 예ㅁ 우ㅁ 주 안ㅁ 있ㅁ 영ㅁㅁㅁㅁ.",
     @"한 번 죽ㅁ 것ㅁ 사ㅁㅁㅁ 정ㅁㅁ 것ㅁㅁ, 그 후ㅁㅁ 심ㅁㅁ 있ㅁㅁㅁ.",
     @"우ㅁㅁ 아ㅁ 죄ㅁ 되ㅁㅁ 때ㅁ 그ㅁㅁㅁㅁㅁ 우ㅁㅁ 위ㅁㅁ 죽ㅁㅁㅁㅁ 하ㅁㅁㅁㅁ 우ㅁㅁㅁ 대ㅁ 자ㅁㅁ 사ㅁㅁ 확ㅁㅁㅁㅁㅁㅁ.",
     @"그ㅁㅁㅁㅁㅁㅁ 한 번 죄ㅁ 위ㅁㅁ 죽ㅁㅁ 의ㅁㅁㅁㅁ 불ㅁㅁ 자ㅁ 대ㅁㅁㅁㅁㅁ, 이ㅁ 우ㅁㅁ 하ㅁㅁ 앞ㅁㅁ 인ㅁㅁㅁ 하ㅁㅁㅁ. 육ㅁㅁㅁ 죽ㅁㅁ 당ㅁㅁㅁ 영ㅁㅁㅁ 살ㅁㅁㅁ 받ㅁㅁㅁㅁ.",
     @"너ㅁㅁ 그 은ㅁㅁ 인ㅁㅁ 믿ㅁㅁㅁ 말ㅁㅁㅁ 구ㅁㅁ 얻ㅁㅁㅁ, 이ㅁㅁ 너ㅁㅁㅁㅁ 난 것ㅁ 아ㅁㅁ 하ㅁㅁㅁ 선ㅁㅁㅁ. 행ㅁㅁㅁ 난 것ㅁ 아ㅁㅁ, 이ㅁ 누ㅁㅁㅁ 자ㅁㅁ못ㅁㅁ 함ㅁㅁㅁ.",
     @"우ㅁㅁ 구ㅁㅁㅁㅁ 우ㅁㅁ 행ㅁㅁ 의ㅁㅁ 행ㅁㅁ 말ㅁㅁㅁ 아ㅁㅁㅁ, 오ㅁ 그ㅁ 긍ㅁㅁㅁㅁ 좇ㅁ 중ㅁㅁ 씻ㅁㅁ 성ㅁㅁ 새ㅁㅁ 하ㅁㅁㅁ 하ㅁㅁㅁ.",
     @"영ㅁㅁㅁ 자 곧 그 이ㅁㅁ 믿ㅁ 자ㅁㅁㅁㅁ 하ㅁㅁㅁ 자ㅁㅁ 되ㅁ 권ㅁㅁ 주ㅁㅁㅁ.",
     @"볼ㅁㅁㅁ. 내ㅁ 문ㅁㅁ 서ㅁ 두ㅁㅁㅁㅁ, 누ㅁㅁㅁ 내 음ㅁㅁ 듣ㅁ 문ㅁ 열ㅁ 내ㅁ 그ㅁㅁㅁ 들ㅁㅁ 그ㅁ 더ㅁㅁ 먹ㅁ 그ㅁ 나ㅁ 더ㅁㅁ 먹ㅁㅁㅁ.",
     @"내ㅁ 하ㅁㅁㅁ 아ㅁㅁ 이ㅁㅁ 믿ㅁ 너ㅁㅁㅁ 이ㅁㅁ 쓴 것ㅁ, 너ㅁㅁ 하ㅁㅁ 너ㅁㅁㅁ 영ㅁㅁ 있ㅁㅁ 알ㅁ 하ㅁ 함ㅁㅁ.",
     @"내ㅁ 진ㅁㅁ 진ㅁㅁ 너ㅁㅁㅁ 이ㅁㅁㅁ, 내 말ㅁ 듣ㅁ 또 나 보ㅁㅁ 이ㅁ 믿ㅁ 자ㅁ 영ㅁㅁ 얻ㅁㅁ 심ㅁㅁ 이ㅁㅁ 아ㅁㅁㅁㅁ 사ㅁㅁㅁ 생ㅁㅁㅁ 옮ㅁㅁㅁㅁ.",},

    {@"너ㅁㅁ 하ㅁㅁㅁ 성ㅁㅁ 것ㅁ 하ㅁㅁㅁ 성ㅁㅁ 너ㅁ 안ㅁ 거ㅁㅁㅁ 것ㅁ 알ㅁ 못ㅁㅁㅁ.",
     @"우ㅁㅁ 세ㅁㅁ 영ㅁ 받ㅁ 아ㅁㅁㅁ 오ㅁ 하ㅁㅁㅁㅁ 온 영ㅁ 받ㅁㅁㅁ, 이ㅁ 우ㅁㅁ 하ㅁㅁ 하ㅁㅁㅁㅁ 우ㅁㅁㅁ 은ㅁㅁ 주ㅁ 것ㅁㅁ 알ㅁ 하ㅁ 하ㅁㅁㅁ.",
     @"두ㅁㅁ 말ㅁ. 내ㅁ 너ㅁ 함ㅁㅁㅁㅁㅁ. 놀ㅁㅁ 말ㅁ. 나ㅁ 네 하ㅁㅁㅁ 됨ㅁㅁㅁ. 내ㅁ 너ㅁ 굳ㅁㅁ 하ㅁㅁ. 참ㅁㅁ 너ㅁ 도ㅁㅁㅁㅁ. 참ㅁㅁ 나ㅁ 의ㅁㅁ 오ㅁㅁㅁㅁ 너ㅁ 붙ㅁㅁㅁ.",
     @"내ㅁ 능ㅁ 주ㅁㅁ 자 안ㅁㅁ 내ㅁ 모ㅁ 것ㅁ 할 수 있ㅁㅁㅁ.",
     @"여ㅁㅁㅁ 자ㅁㅁ 긍ㅁㅁ 무ㅁㅁㅁㅁㅁ 우ㅁㅁ 진ㅁㅁㅁ 아ㅁㅁㅁㅁㅁㅁ. 이ㅁㅁ 아ㅁㅁㅁ 새ㅁㅁㅁ 주ㅁ 성ㅁㅁ 크ㅁㅁㅁㅁ.",
     @"하ㅁㅁㅁ 인ㅁㅁ 아ㅁㅁㅁ 식ㅁㅁ 않ㅁㅁㅁ 인ㅁㅁ 아ㅁㅁㅁ 후ㅁㅁ 없ㅁㅁㅁㅁ. 어ㅁ 그 말ㅁㅁㅁ 바ㅁ 행ㅁ 않ㅁㅁㅁ 하ㅁ 말ㅁㅁ 실ㅁㅁ 않ㅁㅁㅁ.",
     @"주ㅁㅁ 심ㅁㅁ 견ㅁㅁ 자ㅁ 평ㅁㅁ 평ㅁㅁㅁ 지ㅁㅁㅁㅁ, 이ㅁ 그ㅁ 주ㅁ 의ㅁㅁㅁㅁㅁㅁ.",
     @"너ㅁ 염ㅁㅁ 다 주ㅁ 맡ㅁ 버ㅁㅁ. 이ㅁ 저ㅁ 너ㅁㅁ 권ㅁㅁㅁㅁㅁㅁ.",
     @"자ㅁ 아ㅁㅁ 아ㅁㅁ 아ㅁㅁㅁㅁ 우ㅁ 모ㅁ 사ㅁㅁ 위ㅁㅁ 내ㅁ 주ㅁ 이ㅁ 어ㅁ 그 아ㅁㅁ 함ㅁ 모ㅁ 것ㅁ 우ㅁㅁㅁ 은ㅁㅁ 주ㅁ 아ㅁㅁㅁㅁㅁㅁ.",
     @"나ㅁ 하ㅁㅁㅁ 그ㅁㅁㅁ 예ㅁ 안ㅁㅁ 영ㅁ 가ㅁㅁ 그 풍ㅁㅁ 대ㅁ 너ㅁ 모ㅁ 쓸 것ㅁ 채ㅁㅁㅁㅁ.",
     @"자ㅁㅁ 시ㅁㅁ 받ㅁ 고ㅁㅁ 당ㅁㅁㅁㅁ 시ㅁㅁㅁ 자ㅁㅁ 능ㅁ 도ㅁㅁㅁㅁㅁ.",
     @"청ㅁㅁ 무ㅁㅁㅁ 그 행ㅁㅁ 깨ㅁㅁ 하ㅁㅁㅁ. 주ㅁ 말ㅁㅁ 따ㅁ 삼ㅁ 것ㅁㅁㅁㅁ. 내ㅁ 주ㅁ 범ㅁㅁ 아ㅁㅁㅁ 하ㅁ 주ㅁ 말ㅁㅁ 내 마ㅁㅁ 두ㅁㅁㅁㅁ.",},

    {@"너ㅁㅁ 먼ㅁ 그ㅁ 나ㅁㅁ 그ㅁ 의ㅁ 구ㅁㅁ. 그ㅁㅁㅁ 이 모ㅁ 것ㅁ 너ㅁㅁㅁ 더ㅁㅁㅁㅁ.",
     @"또 무ㅁㅁㅁ 이ㅁㅁㅁ, 아ㅁㅁㅁ 나ㅁ 따ㅁㅁㅁㅁㅁ 자ㅁㅁ 부ㅁㅁㅁ 날ㅁㅁ 제 십ㅁㅁㅁ 지ㅁ 나ㅁ 좇ㅁ 것ㅁㅁㅁ.",
     @"이 세ㅁㅁㅁ 세ㅁㅁ 있ㅁ 것ㅁㅁ 사ㅁㅁ 말ㅁ. 누ㅁㅁㅁ 세ㅁㅁ 사ㅁㅁㅁ 아ㅁㅁㅁ 사ㅁㅁ 그 ㅁㅁ 있ㅁ 아ㅁㅁㅁ, 이ㅁ 세ㅁㅁ 있ㅁ 모ㅁ 것ㅁ 육ㅁㅁ 정ㅁㅁ 안ㅁㅁ 정ㅁㅁ 이ㅁㅁ 자ㅁㅁㅁ, 다 아ㅁㅁㅁㅁ 좇ㅁ 온 것ㅁ 아ㅁㅁ 세ㅁㅁㅁ 좇ㅁ 온 것ㅁㅁ.",
     @"너ㅁㅁ 이 세ㅁㅁ 본ㅁㅁ 말ㅁ 오ㅁ 마ㅁㅁ 새ㅁㅁ 함ㅁㅁ 변ㅁㅁ 받ㅁ 하ㅁㅁㅁ 선ㅁㅁㅁ 기ㅁㅁㅁㅁ 온ㅁㅁㅁ 뜻ㅁ 무ㅁㅁㅁ 분ㅁㅁㅁㅁ 하ㅁ.",
     @"그ㅁㅁㅁ 내 사ㅁㅁㅁ 형ㅁㅁㅁ, 견ㅁㅁㅁ 흔ㅁㅁㅁ 말ㅁ 항ㅁ 주ㅁ 일ㅁ 더ㅁ 힘ㅁㅁ 자ㅁㅁ 되ㅁ. 이ㅁ 너ㅁ 수ㅁㅁ 주 안ㅁㅁ 헛ㅁㅁ 않ㅁ 줄ㅁ 앎ㅁㅁㅁ.",
     @"너ㅁㅁ 피ㅁㅁㅁ 낙ㅁㅁ 않ㅁ 위ㅁㅁ 죄ㅁㅁㅁ 이ㅁㅁ 자ㅁㅁㅁ 거ㅁㅁ 일ㅁ 참ㅁㅁㅁㅁ 생ㅁㅁㅁ.",
     @"인ㅁㅁ 온 것ㅁ 섬ㅁㅁ 받ㅁㅁ 함ㅁ 아ㅁㅁ 도ㅁㅁ 섬ㅁㅁ 하ㅁ 자ㅁ 목ㅁㅁ 많ㅁ 사ㅁㅁ 대ㅁㅁㅁ 주ㅁ 함ㅁㅁㅁ.",
     @"우ㅁㅁ 우ㅁㅁ 전ㅁㅁㅁ 것ㅁ 아ㅁㅁ 오ㅁ 그ㅁㅁㅁ 예ㅁㅁ 주 되ㅁ 것ㅁ 또 예ㅁㅁ 위ㅁㅁ 우ㅁㅁ 너ㅁㅁ 종 된 것ㅁ 전ㅁㅁㅁㅁ.",
     @"네 재ㅁㅁ 네 소ㅁㅁㅁ 처ㅁ 익ㅁ 열ㅁㅁ 여ㅁㅁㅁ 공ㅁㅁㅁ. 그ㅁㅁㅁ 네 창ㅁㅁ 가ㅁㅁ 차ㅁ 네 즙ㅁㅁ 새 포ㅁㅁㅁ 넘ㅁㅁㅁ.",
     @"이ㅁㅁ 곧 적ㅁ 심ㅁ 자ㅁ 적ㅁ 거ㅁㅁ 많ㅁ 심ㅁ 자ㅁ 많ㅁ 거ㅁㅁ 하ㅁ 말ㅁㅁㅁ. 각ㅁ 그 마ㅁㅁ 정ㅁ 대ㅁ 할 것ㅁㅁ 인ㅁㅁㅁㅁㅁ 억ㅁㅁ 하ㅁ 말ㅁㅁ 하ㅁㅁㅁ 즐ㅁ 내ㅁ 자ㅁ 사ㅁㅁㅁㅁㅁㅁ.",
     @"오ㅁ 성ㅁㅁ 너ㅁㅁㅁ 임ㅁㅁㅁ 너ㅁㅁ 권ㅁㅁ 받ㅁ 예ㅁㅁㅁㅁ 온 유ㅁㅁ 사ㅁㅁㅁㅁ 땅 끝ㅁㅁ 이ㅁㅁ 내 증ㅁㅁ 되ㅁㅁ 하ㅁㅁㅁ.",
     @"그ㅁㅁㅁ 너ㅁㅁ 가ㅁ 모ㅁ 족ㅁㅁㅁ 제ㅁㅁ 삼ㅁ 아ㅁㅁㅁ 아ㅁㅁ 성ㅁㅁ 이ㅁㅁㅁ 세ㅁㅁ 주ㅁ, 내ㅁ 너ㅁㅁㅁ 분ㅁㅁ 모ㅁ 것ㅁ 가ㅁㅁ 지ㅁㅁ 하ㅁ. 볼ㅁㅁㅁ. 내ㅁ 세ㅁ 끝 날ㅁㅁ 너ㅁㅁ 항ㅁ 함ㅁ 있ㅁㅁㅁ 하ㅁㅁㅁ.",},

    {@"새 계ㅁㅁ 너ㅁㅁㅁ 주ㅁㅁ 서ㅁ 사ㅁㅁㅁ. 내ㅁ 너ㅁㅁ 사ㅁㅁ 것ㅁㅁ 너ㅁㅁ 서ㅁ 사ㅁㅁㅁ. 너ㅁㅁ 서ㅁ 사ㅁㅁㅁ 이ㅁㅁ 모ㅁ 사ㅁㅁ 너ㅁㅁ 내 제ㅁㅁ 줄 알ㅁㅁ.",
     @"자ㅁㅁㅁ, 우ㅁㅁ 말ㅁ 혀ㅁㅁ 사ㅁㅁㅁ 말ㅁ 오ㅁ 행ㅁㅁ 진ㅁㅁㅁㅁ 하ㅁ.",
     @"아ㅁ 일ㅁㅁㅁ 다ㅁㅁㅁ 허ㅁㅁㅁ 하ㅁ 말ㅁ 오ㅁ 겸ㅁㅁ 마ㅁㅁㅁ 각ㅁ 자ㅁㅁㅁ 남ㅁ 낫ㅁ 여ㅁㅁ, 각ㅁ 자ㅁ 일ㅁ 돌ㅁㅁ 뿐ㅁㅁ 또ㅁ 각ㅁ 다ㅁ 사ㅁㅁㅁ 일ㅁ 돌ㅁㅁㅁ 나ㅁ 기ㅁㅁ 충ㅁㅁ 하ㅁ.",
     @"젊ㅁ 자ㅁㅁ, 이ㅁ 같ㅁ 장ㅁㅁㅁㅁ 순ㅁㅁㅁ 다 서ㅁ 겸ㅁㅁㅁ 허ㅁㅁ 동ㅁㅁ. 하ㅁㅁㅁ 교ㅁㅁ 자ㅁ 대ㅁㅁㅁㅁ 겸ㅁㅁ 자ㅁㅁㅁㅁ 은ㅁㅁ 주ㅁㅁㅁㅁ. 그ㅁㅁㅁ 하ㅁㅁㅁ 능ㅁㅁ 손 아ㅁㅁ 겸ㅁㅁㅁ. 때ㅁ 되ㅁ 너ㅁㅁ 높ㅁㅁㅁㅁ.",
     @"음ㅁㅁ 온ㅁ 더ㅁㅁ 것ㅁ 탐ㅁㅁ 너ㅁ 중ㅁㅁ 그 이ㅁㅁㅁㅁ 부ㅁㅁ 말ㅁ. 이ㅁ 성ㅁㅁ 마ㅁㅁ 바ㅁㅁ.",
     @"사ㅁㅁㅁ 자ㅁㅁ, 나ㅁㅁㅁ 행ㅁ 같ㅁ 너ㅁㅁ 권ㅁㅁㅁ 영ㅁㅁ 거ㅁㅁ 싸ㅁㅁ 육ㅁㅁ 정ㅁㅁ 제ㅁㅁㅁ.",
     @"너ㅁㅁ 도ㅁㅁㅁㅁ 말ㅁ, 속ㅁㅁ 말ㅁ, 서ㅁ 거ㅁㅁㅁㅁ 말ㅁ.",
     @"이ㅁㅁ 인ㅁㅁ 나ㅁ 하ㅁㅁㅁ 사ㅁㅁ 대ㅁㅁ 항ㅁ 양ㅁㅁ 거ㅁㅁㅁ 없ㅁㅁ 힘ㅁㅁㅁ.",
     @"믿ㅁㅁ 없ㅁㅁ 기ㅁㅁㅁ 못ㅁㅁㅁ, 하ㅁㅁㅁ 나ㅁㅁㅁ 자ㅁ 반ㅁㅁ 그ㅁ 계ㅁ 것ㅁ 또ㅁ 그ㅁ 자ㅁㅁ 찾ㅁ 자ㅁㅁㅁ 상 주ㅁㅁ 이ㅁㅁ 믿ㅁㅁ 할ㅁㅁㅁ.",
     @"믿ㅁㅁ 없ㅁ 하ㅁㅁㅁ 약ㅁㅁ 의ㅁㅁ 않ㅁ, 믿ㅁㅁ 견ㅁㅁㅁㅁㅁ 하ㅁㅁㅁ 영ㅁㅁ 돌ㅁㅁ, 약ㅁㅁㅁ 그ㅁㅁ 또ㅁ 능ㅁ 이ㅁㅁ 줄ㅁ 확ㅁㅁㅁㅁㅁ.",
     @"우ㅁㅁ 선ㅁ 행ㅁㅁ 낙ㅁㅁㅁ 말ㅁㅁ 피ㅁㅁㅁ 아ㅁㅁㅁ 때ㅁ 이ㅁㅁ 거ㅁㅁㅁ. 그ㅁㅁㅁ 우ㅁㅁ 기ㅁ 있ㅁ ㅁㅁ 모ㅁ 이ㅁㅁ 착ㅁ 일ㅁ 하ㅁ 더ㅁ 믿ㅁㅁ 가ㅁㅁㅁㅁ 할ㅁㅁㅁ.",
     @"이ㅁㅁ 너ㅁ 빛ㅁ 사ㅁ 앞ㅁ 비ㅁㅁ 하ㅁ 저ㅁㅁ 너ㅁ 착ㅁ 행ㅁㅁ 보ㅁ 하ㅁㅁ 계ㅁ 너ㅁ 아ㅁㅁㅁ 영ㅁㅁ 돌ㅁㅁ 하ㅁ.",},
};

NSString* const korHideTextString[5][12] =
{
    {@"ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁ.ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁㅁ, ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ. ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ, ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ, ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ. ㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ. ㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ, ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ. ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",},

    {@"ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ, ㅁㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ, ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁㅁㅁㅁ ㅁ ㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ, ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁ ㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁ, ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁ ㅁㅁ ㅁㅁ ㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ.",},

    {@"ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ. ㅁㅁㅁ ㅁㅁ. ㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ. ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ. ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁ ㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ. ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ. ㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ, ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ.",},

    {@"ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ. ㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ, ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ, ㅁ ㅁㅁㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁ ㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ. ㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ, ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ. ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ.",},

    {@"ㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ. ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ, ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ, ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ.",
     @"ㅁㅁ ㅁㅁㅁ, ㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ. ㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ.",
     @"ㅁㅁㅁㅁ ㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ, ㅁㅁㅁ ㅁㅁ, ㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ, ㅁㅁㅁ ㅁㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ, ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁ. ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁㅁㅁㅁ ㅁㅁㅁㅁ.",
     @"ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁㅁ ㅁㅁ ㅁㅁ ㅁㅁㅁㅁ ㅁㅁㅁ ㅁㅁㅁ ㅁㅁ.",},
};


NSString* const engCategoryString[5] =
{
    @"A. Live the New Life",
    @"B. Proclaim Christ",
    @"C. Rely on God\'s Resource",
    @"D. Be Christ\'s Disciple",
    @"E. Grow in Christlikeness",
};

NSString* const engTitleString[5][12] =
{
    {@"Corinthians 5:17",
     @"Galatians 2:20",
     @"Romans 12:1",
     @"John 14:21",
     @"2 Timothy 3:16",
     @"Joshua 1:8",
     @"John 15:7",
     @"Philippians 4:6-7",
     @"Matthew 18:20",
     @"Hebrews 10:24-25",
     @"Matthew 4:19",
     @"Romans 1:16",},
    
    {@"Romans 3:23",
     @"Isaiah 53:6",
     @"Romans 6:23",
     @"Hebrews 9:27",
     @"Romans 5:8",
     @"1 Peter 3:18",
     @"Ephesians 2:8-9",
     @"Titus 3:5",
     @"John 1:12",
     @"Revelation 3:20",
     @"1 John 5:13",
     @"John 5:24",},
    
    {@"1 Corinthians 3:16",
     @"1 Corinthians 2:12",
     @"Isaiah 41:10",
     @"Philippians 4:13",
     @"Lamentations 3:22-23",
     @"Numbers 23:19",
     @"Isaiah 26:3",
     @"1 Peter 5:7",
     @"Romans 8:32",
     @"Philippians 4:19",
     @"Hebrews 2:18",
     @"Psalm 119:9,11",},
    
    {@"Matthew 6:33",
     @"Luke 9:23",
     @"1 John 2:15-16",
     @"Romans 12:2",
     @"1 Corinthians 15:58",
     @"Hebrews 12:3",
     @"Mark 10:45",
     @"2 Corinthians 4:5",
     @"Proverbs 3:9-10",
     @"2 Corinthians 9:6-7",
     @"Acts 1:8",
     @"Matthew 28:19-20",},
    
    {@"John 13:34,35",
     @"1 John 3:18",
     @"Philippians 2:3-4",
     @"1 Peter 5:5-6",
     @"Ephesians 5:3",
     @"1 Peter 2:11",
     @"Leviticus 19:11",
     @"Acts 24:16",
     @"Hebrews 11:6",
     @"Romans 4:20-21",
     @"Galatians 6:9-10",
     @"Matthew 5:16",},
};

NSString* const engMidTitleString[5][6] =
{
    {@"Christ, the center",
     @"Obedience to Christ",
     @"The Word",
     @"Prayer",
     @"Fellowship",
     @"Witnessing",},
    
    {@"All have Sinned",
     @"Sin\'s Penalty",
     @"Christ Paid the Penalty",
     @"Salvation not by work",
     @"Must receive Christ",
     @"Assurance of Salvation",},
    
    {@"His Spirit",
     @"His Strength",
     @"His Faithfulness",
     @"His peace",
     @"His Provision",
     @"His help in Temptation",},
    
    {@"Put Christ First",
     @"Separate from the World",
     @"Be Steadfast",
     @"Serve Others",
     @"Give Generously",
     @"Develop World Vision",},
    
    {@"Love",
     @"Humility",
     @"Purity",
     @"Honesty",
     @"Faith",
     @"Good Deeds",},
};

NSString* const engTextString[5][12] =
{
    {@"Therefore, if anyone is in Christ, he is a new creation; the old has gone, the new has come!",
     @"I have been crucified with Christ and I no longer live, but Christ lives in me. The life I live in the body, I live by faith in the Son of God, who loves me and gave Himself for me.",
     @"Therefore, I urge you, brothers, in view of God\'s mercy, to offer your bodies as living sacrifices, holy and pleasing to God-this is your spiritual act of worship.",
     @"Whoever has my commands and obeys them, he is the one who loves me. He who loves me will be loved by my Father, and I too will love him and show myself to him.",
     @"All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.",
     @"Do not let this Book of the Law depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it. Then you will be prosperous and successful.",
     @"If you remain in me and my words remain in you, ask whatever you wish, and it will be given you.",
     @"Do not be anxious about anything, but in everything, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
     @"For where two or three come together in my name, there am I with them.",
     @"And let us consider how we may spur one another on toward love and good deeds. Let us not give up meeting together, as some are in the habit of doing, but let us encourage one another-and all the more as you see the Day approaching.",
     @"Come, follow me, Jesus said, \"and I will make you fishers of men.\"",
     @"I am not ashamed of the gospel, because it is the power of God for the salvation of everyone who believes: first for the Jew, then for the Gentile.",},
    
    {@"For all have sinned and fall short of the glory of God.",
     @"We all, like sheep, have gone astray, each of us has turned to his own way; and the Lord has laid on him the iniquity of us all.",
     @"For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.",
     @"Just as man is destined to die once, and after that to face judgment.",
     @"But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
     @"For Christ died for sins once for all, the righteous for the unrighteous, to bring you to God. He was put to death in the body but made alive by the Spirit.",
     @"For it is by grace you have been saved, through faith-and this not from yourselves, it is the gift of God-not by works, so that no one can boast.",
     @"He saved us, not because of righteous things we had done, but because of his mercy. He saved us through the washing of rebirth and renewal by the Holy Spirit.",
     @"Yet to all who received him, to those who believed in his name, he gave the right to become children of God.",
     @"Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with him, and he with me.",
     @"I write these things to you who believe in the name of the Son of God so that you may know that you have eternal life.",
     @"I tell you the truth, whoever hears my word and believes him who sent me has eternal life and will not be condemned; he has crossed over from death to life.",},
 
    {@"Don\'t you know that you yourselves are God\'s temple and that God\'s Spirit lives in you?",
     @"We have not received the spirit of the world but the Spirit who is from God, that we may understand what God has freely given us.",
     @"So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
     @"I can do everything through him who gives me strength.",
     @"Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
     @"God is not a man, that he should lie, nor a son of man, that he should change his mind. Does he speak and then not act? Does he promise and not fulfill?",
     @"You will keep in perfect peace him whose mind is steadfast, because he trusts in you.",
     @"Cast all your anxiety on him because he cares for you.",
     @"He who did not spare his own Son, but gave him up for us all-how will he not also, along with him, graciously give us all things?",
     @"And my God will meet all your needs according to his glorious riches in Christ Jesus.",
     @"Because he himself suffered when he was tempted, he is able to help those who are being tempted.",
     @"How can a young man keep his way pure? By living according to your word. I have hidden your word in my heart that I might not sin against you.",},
    
    {@"But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
     @"Then he said to them all: \"If anyone would come after me, he must deny himself and take up his cross daily and follow me.\"",
     @"Do not love the world or anything in the world. If anyone loves the world, the love of the Father is not in him. For everything in the world-the cravings of sinful man, the lust of his eyes and the boasting of what he has and does-comes not from the Father but from the world.",
     @"Do not conform any longer to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God\'s will is-his good, pleasing and perfect will.",
     @"Therefore, my dear brothers, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.",
     @"Consider him who endured such opposition from sinful men, so that you will not grow weary and lose heart.",
     @"For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.",
     @"For we do not preach ourselves, but Jesus Christ as Lord, and ourselves as your servants for Jesus\' sake.",
     @"Honor the LORD with your wealth, with the first fruits of all your crops; then your barns will be filled to overflowing, and your vats will brim over with new wine.",
     @"Remember this: Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously. Each man should give what he has decided in his heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.",
     @"But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.",
     @"Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.",},
    
    {@"A new command I give you: Love one another. As I have loved you, so you must love one another. By this all men will know that you are my disciples, if you love one another.",
     @"Dear children, let us not love with words or tongue but with actions and in truth.",
     @"Do nothing out of selfish ambition or vain conceit, but in humility consider others better than yourselves. Each of you should look not only to your own interests, but also to the interests of others.",
     @"Young men, in the same way be submissive to those who are older. All of you, clothe yourselves with humility toward one another, because, \"God opposes the proud but gives grace to the humble.\" Humble yourselves, therefore, under God\'s mighty hand, that he may lift you up in due time.",
     @"But among you there must not be even a hint of sexual immorality, or of any kind of impurity, or of greed, because these are improper for God\'s holy people.",
     @"Dear friends, I urge you, as aliens and strangers in the world, to abstain from sinful desires, which war against your soul.",
     @"Do not steal. Do not lie. Do not deceive one another.",
     @"So I strive always to keep my conscience clear before God and man.",
     @"And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.",
     @"Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God, being fully persuaded that God had power to do what he had promised.",
     @"Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. Therefore, as we have opportunity, let us do good to all people, especially to those who belong to the family of believers.",
     @"In the same way, let your light shine before men, that they may see your good deeds and praise your Father in heaven.",},
};

NSString* const engHintTextString[5][12] =
{
    {@"T********, i* a***** i* i* C*****, h* i* a n** c******** t** o** h** g***, t** n** h** c***!",
     @"I h*** b*** c******** w*** C***** a** I n* l***** l***, b** C***** l**** i* m*. T** l*** I l*** i* t** b***, I l*** b* f**** i* t** S** o* G**, w** l**** m* a** g*** H****** f** m*.",
     @"T********, I u*** y**, b*******, i* v*** o* G**** m****, t* o**** y*** b***** a* l***** s*********, h*** a** p******* t* G******* i* y*** s******** a** o* w******.",
     @"W****** h** m* c******* a** o**** t***, h* i* t** o** w** l**** m*. H* w** l**** m* w*** b* l**** b* m* F*****, a** I t** w*** l*** h** a** s*** m***** t* h**.",
     @"A** S******** i* G*********** a** i* u***** f** t*******, r*******, c********* a** t******* i* r************.",
     @"D* n** l** t*** B*** o* t** L** d***** f*** y*** m***** m******* o* i* d** a** n****, s* t*** y** m** b* c****** t* d* e********* w****** i* i*. T*** y** w*** b* p********* a** s*********.",
     @"I* y** r***** i* m* a** m* w**** r***** i* y**, a** w******* y** w***, a** i* w*** b* g**** y**.",
     @"D* n** b* a****** a**** a*******, b** i* e*********, b* p***** a** p*******, w*** t***********, p****** y*** r******* t* G**. A** t** p**** o* G**, w**** t********* a** u************, w*** g**** y*** h***** a** y*** m**** i* C***** J****.",
     @"F** w**** t** o* t**** c*** t******* i* m* n***, t**** a* I w*** t***.",
     @"A** l** u* c******* h** w* m** s*** o** a****** o* t***** l*** a** g*** d****. L** u* n** g*** u* m****** t*******, a* s*** a** i* t** h**** o* d****, b** l** u* e******** o** a********** a** t** m*** a* y** s** t** D** a**********.",
     @"C***, f***** m*, J**** s***, \"a** I w*** m*** y** f****** o* m**.\"",
     @"I a* n** a****** o* t** g*****, b****** i* i* t** p**** o* G** f** t** s******** o* e******* w** b******** f**** f** t** J**, t*** f** t** G******.",},
    
    {@"F** a** h*** s***** a** f*** s**** o* t** g**** o* G**.",
     @"W* a**, l*** s****, h*** g*** a*****, e*** o* u* h** t***** t* h** o** w*** a** t** L*** h** l*** o* h** t** i******* o* u* a**.",
     @"F** t** w**** o* s** i* d****, b** t** g*** o* G** i* e****** l*** i* C***** J**** o** L***.",
     @"J*** a* m** i* d******* t* d** o***, a** a**** t*** t* f*** j*******.",
     @"B** G** d*********** h** o** l*** f** u* i* t**** W**** w* w*** s**** s******, C***** d*** f** u*.",
     @"F** C***** d*** f** s*** o*** f** a**, t** r******** f** t** u**********, t* b**** y** t* G**. H* w** p** t* d**** i* t** b*** b** m*** a**** b* t** S*****.",
     @"F** i* i* b* g**** y** h*** b*** s****, t****** f******** t*** n** f*** y*********, i* i* t** g*** o* G****** b* w****, s* t*** n* o** c** b****.",
     @"H* s**** u*, n** b****** o* r******** t***** w* h** d***, b** b****** o* h** m****. H* s**** u* t****** t** w****** o* r****** a** r****** b* t** H*** S*****.",
     @"Y** t* a** w** r******* h**, t* t**** w** b******* i* h** n***, h* g*** t** r**** t* b***** c******* o* G**.",
     @"H*** I a*! I s**** a* t** d*** a** k****. I* a***** h**** m* v**** a** o**** t** d***, I w*** c*** i* a** e** w*** h**, a** h* w*** m*.",
     @"I w**** t**** t***** t* y** w** b****** i* t** n*** o* t** S** o* G** s* t*** y** m** k*** t*** y** h*** e****** l***.",
     @"I t*** y** t** t****, w****** h**** m* w*** a** b******* h** w** s*** m* h** e****** l*** a** w*** n** b* c********* h* h** c****** o*** f*** d**** t* l***.",},
    
    {@"D**** y** k*** t*** y** y********* a** G**** t***** a** t*** G**** S***** l**** i* y**?",
     @"W* h*** n** r******* t** s***** o* t** w**** b** t** S***** w** i* f*** G**, t*** w* m** u********* w*** G** h** f***** g**** u*.",
     @"S* d* n** f***, f** I a* w*** y*** d* n** b* d*******, f** I a* y*** G**. I w*** s********* y** a** h*** y*** I w*** u***** y** w*** m* r******** r**** h***.",
     @"I c** d* e********* t****** h** w** g**** m* s*******.",
     @"B****** o* t** L***** g**** l*** w* a** n** c*******, f** h** c********** n**** f***. T*** a** n** e**** m******* g**** i* y*** f***********.",
     @"G** i* n** a m**, t*** h* s***** l**, n** a s** o* m**, t*** h* s***** c***** h** m***. D*** h* s**** a** t*** n** a**? D*** h* p****** a** n** f******?",
     @"Y** w*** k*** i* p****** p**** h** w**** m*** i* s********, b****** h* t***** i* y**.",
     @"C*** a** y*** a****** o* h** b****** h* c**** f** y**.",
     @"H* w** d** n** s**** h** o** S**, b** g*** h** u* f** u* a****** w*** h* n** a***, a**** w*** h**, g********* g*** u* a** t*****?",
     @"A** m* G** w*** m*** a** y*** n**** a******** t* h** g******* r***** i* C***** J****.",
     @"B****** h* h****** s******* w*** h* w** t******, h* i* a*** t* h*** t**** w** a** b**** t******.",
     @"H** c** a y**** m** k*** h** w** p***? B* l***** a******** t* y*** w***. I h*** h***** y*** w*** i* m* h**** t*** I m**** n** s** a****** y**.",},

    {@"B** s*** f**** h** k****** a** h** r************, a** a** t**** t***** w*** b* g**** t* y** a* w***.",
     @"T*** h* s*** t* t*** a*** \"I* a***** w**** c*** a**** m*, h* m*** d*** h****** a** t*** u* h** c**** d**** a** f***** m*.\"",
     @"D* n** l*** t** w**** o* a******* i* t** w****. I* a***** l**** t** w****, t** l*** o* t** F***** i* n** i* h**. F** e********* i* t** w******** c******* o* s***** m**, t** l*** o* h** e*** a** t** b******* o* w*** h* h** a** d********* n** f*** t** F***** b** f*** t** w****.",
     @"D* n** c****** a** l***** t* t** p****** o* t*** w****, b** b* t********** b* t** r******* o* y*** m***. T*** y** w*** b* a*** t* t*** a** a****** w*** G**** w*** i***** g***, p******* a** p****** w***.",
     @"T********, m* d*** b*******, s**** f***. L** n****** m*** y**. A***** g*** y********* f**** t* t** w*** o* t** L***, b****** y** k*** t*** y*** l**** i* t** L*** i* n** i* v***.",
     @"C******* h** w** e****** s*** o********* f*** s***** m**, s* t*** y** w*** n** g*** w**** a** l*** h****.",
     @"F** e*** t** S** o* M** d** n** c*** t* b* s*****, b** t* s****, a** t* g*** h** l*** a* a r***** f** m***.",
     @"F** w* d* n** p***** o********, b** J**** C***** a* L***, a** o******** a* y*** s******* f** J***** s***.",
     @"H**** t** L*** w*** y*** w*****, w*** t** f********** o* a** y*** c***** t*** y*** b**** w*** b* f***** t* o**********, a** y*** v*** w*** b*** o*** w*** n** w***.",
     @"R******* t**** W****** s*** s******** w*** a*** r*** s********, a** w****** s*** g********* w*** a*** r*** g*********. E*** m** s***** g*** w*** h* h** d****** i* h** h**** t* g***, n** r********** o* u**** c*********, f** G** l**** a c******* g****.",
     @"B** y** w*** r****** p**** w*** t** H*** S***** c**** o* y*** a** y** w*** b* m* w******** i* J********, a** i* a** J**** a** S******, a** t* t** e*** o* t** e****.",
     @"T******** g* a** m*** d******** o* a** n******, b******** t*** i* t** n*** o* t** F***** a** o* t** S** a** o* t** H*** S*****, a** t******* t*** t* o*** e********* I h*** c******** y**. A** s***** I a* w*** y** a*****, t* t** v*** e** o* t** a**.",},
    
    {@"A n** c****** I g*** y*** L*** o** a******. A* I h*** l**** y**, s* y** m*** l*** o** a******. B* t*** a** m** w*** k*** t*** y** a** m* d********, i* y** l*** o** a******.",
     @"D*** c*******, l** u* n** l*** w*** w**** o* t***** b** w*** a****** a** i* t****.",
     @"D* n****** o** o* s****** a******* o* v*** c******, b** i* h******* c******* o***** b***** t*** y*********. E*** o* y** s***** l*** n** o*** t* y*** o** i********, b** a*** t* t** i******** o* o*****.",
     @"Y**** m**, i* t** s*** w** b* s********* t* t**** w** a** o****. A** o* y**, c***** y********* w*** h******* t***** o** a******, b******, \"G** o****** t** p**** b** g**** g**** t* t** h*****.\" H***** y*********, t********, u**** G**** m***** h***, t*** h* m** l*** y** u* i* d** t***.",
     @"B** a**** y** t**** m*** n** b* e*** a h*** o* s***** i*********, o* o* a** k*** o* i*******, o* o* g****, b****** t**** a** i******* f** G**** h*** p*****.",
     @"D*** f******, I u*** y**, a* a***** a** s******** i* t** w****, t* a****** f*** s***** d******, w**** w** a****** y*** s***.",
     @"D* n** s****. D* n** l**. D* n** d****** o** a******.",
     @"S* I s***** a***** t* k*** m* c********* c**** b***** G** a** m**.",
     @"A** w****** f**** i* i* i********* t* p***** G**, b****** a***** w** c**** t* h** m*** b****** t*** h* e***** a** t*** h* r****** t**** w** e******** s*** h**.",
     @"Y** h* d** n** w**** t****** u******* r******** t** p****** o* G**, b** w** s*********** i* h** f**** a** g*** g**** t* G**, b**** f**** p******** t*** G** h** p**** t* d* w*** h* h** p*******.",
     @"L** u* n** b***** w**** i* d**** g***, f** a* t** p***** t*** w* w*** r*** a h****** i* w* d* n** g*** u*. T********, a* w* h*** o**********, l** u* d* g*** t* a** p*****, e********* t* t**** w** b***** t* t** f***** o* b********.",
     @"I* t** s*** w**, l** y*** l**** s**** b***** m**, t*** t*** m** s** y*** g*** d**** a** p***** y*** F***** i* h*****.",},
};
    
NSString* const engHideTextString[5][12] =
{
    {@"*** *** **** ****** *** **** ***** ** *** ***** ** ***.",
     @"** ***, **** *****, **** **** ******, **** ** ** *** ****** ** *** *** **** *** *** **** *** **** ** *** *** ******** ** ** ***.",
     @"*** *** ***** ** *** ** *****, *** *** **** ** *** ** ******* **** ** ****** ***** *** ****.",
     @"**** ** *** ** ******** ** *** ****, *** ***** **** ** **** ********.",
     @"*** *** ************ *** *** **** *** ** ** ***** ***** ** **** ***** *******, ****** **** *** **.",
     @"*** ****** **** *** **** **** *** ***, *** ********* *** *** ***********, ** ***** *** ** ***. ** *** *** ** ***** ** *** **** *** **** ***** ** *** ******.",
     @"*** ** ** ** ***** *** **** **** *****, ******* ********* **** *** **** **********, ** ** *** **** ** ******* ** *****, ** **** ** *** *** *****.",
     @"** ***** **, *** ******* ** ********* ****** ** *** ****, *** ******* ** *** *****. ** ***** ** ******* *** ******* ** ******* *** ******* ** *** **** ******.",
     @"*** ** *** *** ******** ***, ** ***** *** ******** ** *** ****, ** **** *** ***** ** ****** ******** ** ***.",
     @"**** * **! * ***** ** *** **** *** *****. ** ****** ***** ** ***** *** ***** *** ****, * **** **** ** *** *** **** ***, *** ** **** **.",
     @"* ***** ***** ****** ** *** *** ******* ** *** **** ** *** *** ** *** ** **** *** *** **** **** *** **** ******* ****.",
     @"* **** *** *** *****, ******* ***** ** **** *** ******** *** *** **** ** *** ******* **** *** **** *** ** ********** ** *** ******* **** **** ***** ** ****.",},
    
    {@"*********, ** ****** ** ** ******, ** ** * *** ********* *** *** *** ****, *** *** *** ****!",
     @"* **** **** ********* **** ****** *** * ** ****** ****, *** ****** ***** ** **. *** **** * **** ** *** ****, * **** ** ***** ** *** *** ** ***, *** ***** ** *** **** ******* *** **.",
     @"*********, * **** ***, ********, ** **** ** ***** *****, ** ***** **** ****** ** ****** **********, **** *** ******** ** ******** ** **** ********* *** ** *******.",
     @"******* *** ** ******** *** ***** ****, ** ** *** *** *** ***** **. ** *** ***** ** **** ** ***** ** ** ******, *** * *** **** **** *** *** **** ****** ** ***.",
     @"*** ********* ** ************ *** ** ****** *** ********, ********, ********** *** ******** ** *************.",
     @"** *** *** **** **** ** *** *** ****** **** **** ****** ******** ** ** *** *** *****, ** **** *** *** ** ******* ** ** ********** ******* ** **. **** *** **** ** ********** *** **********.",
     @"** *** ****** ** ** *** ** ***** ****** ** ***, *** ******** *** ****, *** ** **** ** ***** ***.",
     @"** *** ** ******* ***** ********, *** ** **********, ** ****** *** ********, **** ************, ******* **** ******** ** ***. *** *** ***** ** ***, ***** ********** *** *************, **** ***** **** ****** *** **** ***** ** ****** *****.",
     @"*** ***** *** ** ***** **** ******** ** ** ****, ***** ** * **** ****.",
     @"*** *** ** ******** *** ** *** **** *** ******* ** ****** **** *** **** *****. *** ** *** **** ** ******* ********, ** **** *** ** *** ***** ** *****, *** *** ** ********* *** *********** *** *** **** ** *** *** *** *** ***********.",
     @"****, ****** **, ***** ****, \"*** * **** **** *** ******* ** ***.\"",
     @"* ** *** ******* ** *** ******, ******* ** ** *** ***** ** *** *** *** ********* ** ******** *** ********* ***** *** *** ***, **** *** *** *******.",},
    
    {@"***** *** **** **** *** ********** *** ***** ****** *** **** ***** ****** ***** ** ***?",
     @"** **** *** ******** *** ****** ** *** ***** *** *** ****** *** ** **** ***, **** ** *** ********** **** *** *** ****** ***** **.",
     @"** ** *** ****, *** * ** **** **** ** *** ** ********, *** * ** **** ***. * **** ********** *** *** **** **** * **** ****** *** **** ** ********* ***** ****.",
     @"* *** ** ********** ******* *** *** ***** ** ********.",
     @"******* ** *** ****** ***** **** ** *** *** ********, *** *** *********** ***** ****. **** *** *** ***** ******** ***** ** **** ************.",
     @"*** ** *** * ***, **** ** ****** ***, *** * *** ** ***, **** ** ****** ****** *** ****. **** ** ***** *** **** *** ***? **** ** ******* *** *** *******?",
     @"*** **** **** ** ******* ***** *** ***** **** ** *********, ******* ** ****** ** ***.",
     @"**** *** **** ******* ** *** ******* ** ***** *** ***.",
     @"** *** *** *** ***** *** *** ***, *** **** *** ** *** ** ******* **** ** *** ****, ***** **** ***, ********** **** ** *** ******?",
     @"*** ** *** **** **** *** **** ***** ********* ** *** ******** ****** ** ****** *****.",
     @"******* ** ******* ******** **** ** *** *******, ** ** **** ** **** ***** *** *** ***** *******.",
     @"*** *** * ***** *** **** *** *** ****? ** ****** ********* ** **** ****. * **** ****** **** **** ** ** ***** **** * ***** *** *** ******* ***.",},
    
    {@"*** **** ***** *** ******* *** *** *************, *** *** ***** ****** **** ** ***** ** *** ** ****.",
     @"**** ** **** ** **** **** \"** ****** ***** **** ***** **, ** **** **** ******* *** **** ** *** ***** ***** *** ****** **.\"",
     @"** *** **** *** ***** ** ******** ** *** *****. ** ****** ***** *** *****, *** **** ** *** ****** ** *** ** ***. *** ********** ** *** ********* ******** ** ****** ***, *** **** ** *** **** *** *** ******** ** **** ** *** *** ********** *** **** *** ****** *** **** *** *****.",
     @"** *** ******* *** ****** ** *** ******* ** **** *****, *** ** *********** ** *** ******** ** **** ****. **** *** **** ** **** ** **** *** ******* **** ***** **** ****** ****, ******** *** ******* ****.",
     @"*********, ** **** ********, ***** ****. *** ******* **** ***. ****** **** ********** ***** ** *** **** ** *** ****, ******* *** **** **** **** ***** ** *** **** ** *** ** ****.",
     @"******** *** *** ******* **** ********** **** ****** ***, ** **** *** **** *** **** ***** *** **** *****.",
     @"*** **** *** *** ** *** *** *** **** ** ** ******, *** ** *****, *** ** **** *** **** ** * ****** *** ****.",
     @"*** ** ** *** ****** *********, *** ***** ****** ** ****, *** ********* ** **** ******** *** ****** ****.",
     @"***** *** **** **** **** ******, **** *** *********** ** *** **** ****** **** **** ***** **** ** ****** ** ***********, *** **** **** **** **** **** **** *** ****.",
     @"******** ***** ******* **** ********* **** **** **** *********, *** ******* **** ********** **** **** **** **********. **** *** ****** **** **** ** *** ******* ** *** ***** ** ****, *** *********** ** ***** **********, *** *** ***** * ******** *****.",
     @"*** *** **** ******* ***** **** *** **** ****** ***** ** **** *** *** **** ** ** ********* ** *********, *** ** *** ***** *** *******, *** ** *** **** ** *** *****.",
     @"********* ** *** **** ********* ** *** *******, ********* **** ** *** **** ** *** ****** *** ** *** *** *** ** *** **** ******, *** ******** **** ** **** ********** * **** ********* ***. *** ****** * ** **** *** ******, ** *** **** *** ** *** ***.",},
    
    {@"* *** ******* * **** **** **** *** *******. ** * **** ***** ***, ** *** **** **** *** *******. ** **** *** *** **** **** **** *** *** ** *********, ** *** **** *** *******.",
     @"**** ********, *** ** *** **** **** ***** ** ****** *** **** ******* *** ** *****.",
     @"** ******* *** ** ******* ******** ** **** *******, *** ** ******** ******** ****** ****** **** **********. **** ** *** ****** **** *** **** ** **** *** *********, *** **** ** *** ********* ** ******.",
     @"***** ***, ** *** **** *** ** ********** ** ***** *** *** *****. *** ** ***, ****** ********** **** ******** ****** *** *******, *******, \"*** ******* *** ***** *** ***** ***** ** *** ******.\" ****** **********, *********, ***** ***** ****** ****, **** ** *** **** *** ** ** *** ****.",
     @"*** ***** *** ***** **** *** ** **** * **** ** ****** **********, ** ** *** **** ** ********, ** ** *****, ******* ***** *** ******** *** ***** **** ******.",
     @"**** *******, * **** ***, ** ****** *** ********* ** *** *****, ** ******* **** ****** *******, ***** *** ******* **** ****.",
     @"** *** *****. ** *** ***. ** *** ******* *** *******.",
     @"** * ****** ****** ** **** ** ********** ***** ****** *** *** ***.",
     @"*** ******* ***** ** ** ********** ** ****** ***, ******* ****** *** ***** ** *** **** ******* **** ** ****** *** **** ** ******* ***** *** ********* **** ***.",
     @"*** ** *** *** ***** ******* ******** ********* *** ******* ** ***, *** *** ************ ** *** ***** *** **** ***** ** ***, ***** ***** ********* **** *** *** ***** ** ** **** ** *** ********.",
     @"*** ** *** ****** ***** ** ***** ****, *** ** *** ****** **** ** **** **** * ******* ** ** ** *** **** **. *********, ** ** **** ***********, *** ** ** **** ** *** ******, ********** ** ***** *** ****** ** *** ****** ** *********.",
     @"** *** **** ***, *** **** ***** ***** ****** ***, **** **** *** *** **** **** ***** *** ****** **** ****** ** ******.",},
};

